[phases.setup]
nixPkgs = ["nodejs_22"]

[variables]
NIXPACKS_NODE_VERSION = "22"
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
